services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_PASS=your_mongoPassword
      - REDIS_PASS=your_redisPassword
      - REDIS_HOST=your_redisHost
      - REDIS_PORT=18963
      - GOOGLE_TRANSLATE_API_KEY=your_googleAPI
    volumes:
      - .:/app
    command: ["node", "server.js"]
